#!/usr/bin/env python3
"""Add mode/bank/index/check columns to kuten_inspector CSV output."""

from __future__ import annotations

import argparse
import csv
import sys
from pathlib import Path


DEFAULT_MODE = "8000"
DEFAULT_CHECK = "1"
FIRST_BANK = 1
MAX_INDEX = 382
RESERVED_INDEXES = {255}
AVAILABLE_INDEXES = [
    index for index in range(MAX_INDEX + 1) if index not in RESERVED_INDEXES
]
ROWS_PER_BANK = len(AVAILABLE_INDEXES)
ADDED_COLUMNS = ["mode", "bank", "index", "check"]


def is_newline_row(row: dict[str, str]) -> bool:
    return row.get("character") == "\n" or row.get("display") == "<LF>"


def bank_index_for_row(row_number: int) -> tuple[int, int]:
    if row_number < 0:
        raise ValueError("row_number must be greater than or equal to zero")
    bank = FIRST_BANK + (row_number // ROWS_PER_BANK)
    index = AVAILABLE_INDEXES[row_number % ROWS_PER_BANK]
    return bank, index


def add_bank_index_columns(
    rows: list[dict[str, str]],
    fieldnames: list[str],
) -> tuple[list[str], list[dict[str, str]]]:
    output_fieldnames = [name for name in fieldnames if name not in ADDED_COLUMNS]
    output_fieldnames.extend(ADDED_COLUMNS)

    output_rows: list[dict[str, str]] = []
    assignable_rows = [row for row in rows if not is_newline_row(row)]
    for row_number, row in enumerate(assignable_rows):
        bank, index = bank_index_for_row(row_number)
        output_row = {name: row.get(name, "") for name in output_fieldnames}
        output_row["mode"] = DEFAULT_MODE
        output_row["bank"] = str(bank)
        output_row["index"] = str(index)
        output_row["check"] = DEFAULT_CHECK
        output_rows.append(output_row)

    return output_fieldnames, output_rows


def read_csv(path: Path) -> tuple[list[str], list[dict[str, str]]]:
    with path.open(encoding="utf-8", newline="") as file:
        reader = csv.DictReader(file)
        if reader.fieldnames is None:
            raise ValueError("input CSV must have a header row")
        return reader.fieldnames, list(reader)


def write_csv(
    path: Path | None,
    fieldnames: list[str],
    rows: list[dict[str, str]],
) -> None:
    output = sys.stdout if path is None else path.open("w", encoding="utf-8", newline="")
    try:
        writer = csv.DictWriter(output, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(rows)
    finally:
        if path is not None:
            output.close()


def parse_args(argv: list[str]) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Add mode, bank, index, and check columns to a character CSV.",
    )
    parser.add_argument(
        "--input",
        type=Path,
        required=True,
        help="CSV generated by kuten_inspector.py.",
    )
    parser.add_argument(
        "--output",
        type=Path,
        help="Output CSV path. Defaults to standard output.",
    )
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    args = parse_args(sys.argv[1:] if argv is None else argv)

    try:
        fieldnames, rows = read_csv(args.input)
        output_fieldnames, output_rows = add_bank_index_columns(rows, fieldnames)
        write_csv(args.output, output_fieldnames, output_rows)
    except (OSError, ValueError) as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 1

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
